require:
  - rubocop-inhouse
  - rubocop-capybara

inherit_gem:
  rubocop-inhouse:
    - config/default.yml
    - config/capybara.yml

AllCops:
  TargetRubyVersion: 3.3

Lint/NumberConversion:
  Enabled: false
