# frozen_string_literal: true

require "vite_ruby"

ViteRuby.install_tasks

desc "Precompile assets"
task :environment do
  require "./config/boot"
end

namespace :site do
  desc "Build the site and its assets into the Staticky.build_path (./build)"
  task build: :environment do
    start_time = Time.now
    puts "Building site in #{Staticky.env.name} environment..."
    Rake::Task["vite:build"].invoke unless Staticky.env.development?
    Staticky.builder.call
    end_time = Time.now
    duration = end_time - start_time
    puts "Built site in #{duration.round(2)}s"
  end

  desc "Watch the site and its assets for changes"
  task watch: :environment do
    require "filewatcher"

    puts "Watching site in #{Staticky.env.name} environment..."

    Filewatcher.new([
      "app/**/*.rb",
      "lib/**/*.rb",
      "content/**/*"
    ]).watch do
      puts "Change detected, rebuilding site..."

      sh("bin/rake site:build") do |ok, res|
        unless ok
          puts "Error rebuilding site:"
          puts res
        end
      end
    end
  end
end
